import * as fs from 'fs';
import * as path from 'path';
import { PacEnvironment, listSolutions } from './pacCli';

export interface CloudIndexFlow {
  name: string;
  displayName: string;
}

export interface CloudIndexSolution {
  uniqueName: string;
  friendlyName: string;
  version: string;
  isManaged: boolean;
  hasSharedDocs: boolean;
  flows: CloudIndexFlow[];
}

export interface CloudIndexEnvironment {
  name: string;
  url: string;
  solutions: CloudIndexSolution[];
}

export interface CloudIndex {
  builtAt: string;
  environments: CloudIndexEnvironment[];
}

function readFlowsFromDisk(workflowsDir: string): CloudIndexFlow[] {
  if (!fs.existsSync(workflowsDir)) { return []; }
  const flows: CloudIndexFlow[] = [];
  for (const f of fs.readdirSync(workflowsDir).filter(f => f.endsWith('.json'))) {
    const rawName = path.basename(f, '.json');
    let displayName = rawName
      .replace(/-[A-F0-9]{8}(?:-[A-F0-9]{4}){3}-[A-F0-9]{12}$/i, '')
      .replace(/-/g, ' ');
    try {
      const flow = JSON.parse(fs.readFileSync(path.join(workflowsDir, f), 'utf8'));
      const dn: unknown = flow?.properties?.displayName;
      if (typeof dn === 'string' && dn.trim()) { displayName = dn.trim(); }
    } catch { /* ignore */ }
    flows.push({ name: rawName, displayName });
  }
  return flows;
}

/**
 * Builds a cloud index by listing all solutions from every environment via pac,
 * and enriches each solution with flow names from locally exported files.
 *
 * @param envs            pac environments
 * @param solutionsRoot   local solutions folder (may be undefined if no workspace open)
 * @param onProgress      optional progress callback
 * @param sharedDocNames  set of solution unique names that have FLOWS.md on SharePoint
 */
export async function buildCloudIndex(
  envs: PacEnvironment[],
  solutionsRoot: string | undefined,
  onProgress?: (msg: string) => void,
  sharedDocNames?: Set<string>
): Promise<CloudIndex> {
  const environments: CloudIndexEnvironment[] = [];

  for (const env of envs) {
    onProgress?.(`Listing solutions in ${env.FriendlyName}…`);
    const solutions: CloudIndexSolution[] = [];

    try {
      const raw = await listSolutions(env.EnvironmentUrl);
      for (const sol of raw) {
        const localDir = solutionsRoot
          ? path.join(solutionsRoot, sol.SolutionUniqueName)
          : undefined;
        const workflowsDir = localDir ? path.join(localDir, 'Workflows') : undefined;
        const flows = workflowsDir ? readFlowsFromDisk(workflowsDir) : [];

        solutions.push({
          uniqueName: sol.SolutionUniqueName,
          friendlyName: sol.FriendlyName,
          version: sol.VersionNumber,
          isManaged: sol.IsManaged,
          hasSharedDocs: sharedDocNames?.has(sol.SolutionUniqueName) ?? false,
          flows,
        });
      }
    } catch (e: any) {
      onProgress?.(`⚠ Could not list solutions for ${env.FriendlyName}: ${e.message}`);
    }

    environments.push({ name: env.FriendlyName, url: env.EnvironmentUrl, solutions });
  }

  return { builtAt: new Date().toISOString(), environments };
}

/**
 * Renders a CloudIndex as a Markdown document suitable for AI context.
 * Unmanaged solutions are separated from managed ones.
 */
export function renderIndexMarkdown(index: CloudIndex): string {
  const lines: string[] = [
    `# DXT Cloud Flow Index`,
    ``,
    `> Last updated: ${index.builtAt.slice(0, 16).replace('T', ' ')} UTC`,
    `> Auto-generated by the DXT Power Automate Toolkit — do not edit manually.`,
    `> Solutions marked 📄 have a FLOWS.md with full documentation on SharePoint.`,
    ``,
  ];

  for (const env of index.environments) {
    const unmanaged = env.solutions.filter(s => !s.isManaged);
    const managed = env.solutions.filter(s => s.isManaged);
    if (!env.solutions.length) { continue; }

    lines.push(`## ${env.name}`, ``);

    if (unmanaged.length) {
      for (const sol of unmanaged) {
        const docsTag = sol.hasSharedDocs ? ' 📄' : '';
        lines.push(`### ${sol.friendlyName}${docsTag}`);
        lines.push(`\`${sol.uniqueName}\` · v${sol.version}`);
        lines.push(``);
        if (sol.flows.length) {
          lines.push(`**Flows (${sol.flows.length}):**`);
          for (const f of sol.flows) {
            lines.push(`- ${f.displayName}`);
          }
        } else {
          lines.push(`_No local flow data — export this solution to index its flows_`);
        }
        lines.push(``);
      }
    }

    if (managed.length) {
      lines.push(
        `<details><summary>Managed solutions (${managed.length})</summary>`,
        ``,
        ...managed.map(s => `- \`${s.uniqueName}\` v${s.version}`),
        ``,
        `</details>`,
        ``
      );
    }
  }

  return lines.join('\n');
}
