import * as fs from 'fs';
import * as path from 'path';

interface FlatAction {
  name: string;
  type: string;
  connector?: string;
  operation?: string;
  depth: number;
}

function getConnector(action: any): string | undefined {
  const apiId: string | undefined = action.inputs?.host?.apiId;
  if (!apiId) { return undefined; }
  return apiId.split('/').pop();
}

function topoSort(actions: Record<string, any>): string[] {
  const visited: Record<string, boolean> = {};
  const order: string[] = [];
  function visit(n: string) {
    if (visited[n]) { return; }
    visited[n] = true;
    const runAfter: Record<string, string[]> = actions[n]?.runAfter ?? {};
    for (const dep in runAfter) {
      if (actions[dep]) { visit(dep); }
    }
    order.push(n);
  }
  for (const n in actions) { visit(n); }
  return order;
}

function flattenActions(actions: Record<string, any>, depth = 0): FlatAction[] {
  if (!actions || typeof actions !== 'object') { return []; }
  const order = topoSort(actions);
  const result: FlatAction[] = [];
  for (const name of order) {
    const a = actions[name];
    result.push({
      name: name.replace(/_/g, ' '),
      type: a.type ?? 'Unknown',
      connector: getConnector(a),
      operation: a.inputs?.host?.operationId,
      depth,
    });
    // Recurse into nested branches
    if (a.actions && typeof a.actions === 'object') {
      result.push(...flattenActions(a.actions, depth + 1));
    }
    if (a.else?.actions && typeof a.else.actions === 'object') {
      result.push(...flattenActions(a.else.actions, depth + 1));
    }
  }
  return result;
}

function hasErrorHandling(actions: Record<string, any>): boolean {
  for (const a of Object.values(actions ?? {}) as any[]) {
    const ra: Record<string, string[]> = a.runAfter ?? {};
    for (const conds of Object.values(ra)) {
      if (conds.some(c => c === 'Failed' || c === 'TimedOut')) { return true; }
    }
    if (a.actions && hasErrorHandling(a.actions)) { return true; }
    if (a.else?.actions && hasErrorHandling(a.else.actions)) { return true; }
  }
  return false;
}

function parseFlowFile(flowFilePath: string): {
  displayName: string;
  triggerLabel: string;
  isHttpTrigger: boolean;
  actions: FlatAction[];
  connectors: string[];
  hasErr: boolean;
} | null {
  try {
    const raw = fs.readFileSync(flowFilePath, 'utf8');
    const flow = JSON.parse(raw);
    const def = flow.properties?.definition ?? flow.definition ?? flow;

    const baseName = path.basename(flowFilePath, '.json');
    const displayName = baseName.replace(/-[A-F0-9]{8}(?:-[A-F0-9]{4}){3}-[A-F0-9]{12}$/i, '').replace(/-/g, ' ');

    const triggers: Record<string, any> = def.triggers ?? {};
    const triggerEntry = Object.values(triggers)[0] as any;
    const triggerType: string = triggerEntry?.type ?? 'Unknown';
    const triggerKind: string | undefined = triggerEntry?.kind;
    const triggerLabel = triggerKind ? `${triggerType}/${triggerKind}` : triggerType;
    const isHttpTrigger = triggerType === 'Request';

    const actions = flattenActions(def.actions ?? {});
    const connectors = [...new Set(actions.map(a => a.connector).filter((c): c is string => !!c))];
    const hasErr = hasErrorHandling(def.actions ?? {});

    return { displayName, triggerLabel, isHttpTrigger, actions, connectors, hasErr };
  } catch {
    return null;
  }
}

export function generateSolutionDocs(solutionsRoot: string): string {
  const solutionDirs = fs.readdirSync(solutionsRoot, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);

  const today = new Date().toISOString().slice(0, 10);
  const lines: string[] = [
    `# Power Automate Solutions — Documentation`,
    ``,
    `> Auto-generated by DXT Power Automate Toolkit on ${today}`,
    ``,
  ];

  for (const solName of solutionDirs) {
    const workflowsDir = path.join(solutionsRoot, solName, 'Workflows');
    if (!fs.existsSync(workflowsDir)) { continue; }

    const flowFiles = fs.readdirSync(workflowsDir).filter(f => f.endsWith('.json'));
    if (!flowFiles.length) { continue; }

    lines.push(`---`, ``);
    lines.push(`## 📦 ${solName}`, ``);
    lines.push(`**${flowFiles.length} flow${flowFiles.length !== 1 ? 's' : ''}**`, ``);

    for (const file of flowFiles) {
      const parsed = parseFlowFile(path.join(workflowsDir, file));
      if (!parsed) {
        lines.push(`### ⚡ ${path.basename(file, '.json')}`, ``, `_Could not parse this flow file._`, ``);
        continue;
      }

      const { displayName, triggerLabel, isHttpTrigger, actions, connectors, hasErr } = parsed;
      const badges: string[] = [];
      if (hasErr) { badges.push('✅ Error handling'); } else { badges.push('⚠️ No error handling'); }
      if (isHttpTrigger) { badges.push('⚠️ Register in APIM'); }

      lines.push(`### ⚡ ${displayName}`, ``);
      if (badges.length) { lines.push(badges.join('&ensp;·&ensp;'), ``); }
      lines.push(`**Trigger:** \`${triggerLabel}\``, ``);

      if (actions.length) {
        lines.push(`| # | Action | Type | Connector | Operation |`);
        lines.push(`|---|--------|------|-----------|-----------|`);
        actions.forEach((a, i) => {
          const indent = '  '.repeat(a.depth);
          lines.push(`| ${i + 1} | ${indent}${a.name} | \`${a.type}\` | ${a.connector ?? '—'} | ${a.operation ?? '—'} |`);
        });
        lines.push(``);
      }

      if (connectors.length) {
        lines.push(`**Connectors used:** ${connectors.join(', ')}`, ``);
      }
    }
  }

  return lines.join('\n');
}
